### ISSUE TITLE
Need help implementing emergency mode

### ISSUE THREAD

**Issue by michaelshmitty** [hybridgroup/cylon-ardrone#25]
I'm using this module in combination with the [cylon-joystick](https://github.com/hybridgroup/cylon-joystick) module. I'd like to assign a button for triggering emergency mode.
I noticed cylon-ardrone does not currently implement this, but the underlying [ar-drone module](https://github.com/felixge/node-ar-drone) by felixge does.
(**Note:** cylon-ardrone *does* support disableEmergency() for recovering from emergency. That is not what I'm after.)
Triggering emergency mode in [felixge's ar-drone](https://github.com/felixge/node-ar-drone) module is done by setting a variable rather than calling a method like so:
```javascript
// Non-cylonjs code
var arDrone = require('ar-drone');
var client = arDrone.createClient();

/**
* Triggers emergency mode, causes drone to cut engines and
* fall from the sky like a brick.
*/
client._ref.emergency = true
```

I volunteer to implement this in cylon-ardrone, but I don't know where to put this or where I can access the instance of arDrone.createClient();

I tried this in Flight.js:
```javascript
// Cylonjs code
/**
 * Tells the drone to enter emergency mode.
 *
 * @return {null}
 * @publish
 */
Flight.prototype.emergency = function() {
  return this.ardrone._ref.emergency = true;
};
```
That doesn't work and returns
```
TypeError: Cannot read property '_ref' of undefined
```
because I'm not talking to the right object.

Can anyone point me in the right direction? Cheers!

**Comment by deadprogram** [comment]
Hi, @michaelshmitty 

I would expect the driver implementation to be more like:
```
Flight.prototype.emergency = function() {
  return this.connection.ardrone._ref.emergency = true;
};
```

Please let me know if that does what you expect.

**Comment by michaelshmitty** [comment]
Cheers for that, I'll try it out and issue a PR if I'm successful in implementing this.

**Comment by deadprogram** [comment]
Thanks for the PR, it has been merged.
