### ISSUE TITLE
Amend documentation

### ISSUE THREAD

**Issue by michaelshmitty** [hybridgroup/cylon-ardrone#28]
The recently added [support for ftrim() and emergency mode](https://github.com/hybridgroup/cylon-ardrone/commit/d5024d4a61d6846bff811847fb4abb5b78b67bdb) is not yet documented on the [cylonjs website](http://cylonjs.com/documentation/drivers/ardrone-flight/).
There are some other commands missing as well, like for example the _backward()_ and _config()_ commands.
Is this documentation generated from the source code or is it added to the [cylonjs.com](http://cylonjs.com/) website manually? In case of the former, can I help to fix this?

**Comment by deadprogram** [comment]
Hi @michaelshmitty 

This contains the instructions on how we import docs via the various repos: https://github.com/hybridgroup/cylon-site#repo-docs

We will probably run this AM to update, but now you know how we do it.

**Comment by deadprogram** [comment]
@zankavrogin can you please handle this?

**Comment by zankavrogin** [comment]
Hey @michaelshmitty
I added the new commands to the site, everything is up to date now!

**Comment by michaelshmitty** [comment]
Hi Nathan ( @zankavrogin ),

Neat, but there seems to be some duplication going on. Several commands are documented twice. Any idea what's up?
See "hover", "ftrim", ... at http://cylonjs.com/documentation/drivers/ardrone-flight/

Also, and this is perhaps a different discussion, there seem to be two commands to move the drone forward (with differing documentation):
```
forward()
Makes the drone bank forwards.
```
and
```
front()
Makes the drone bank forwards.

Controls the pitch and horizontal movement using the camera as a reference point.
```
Is this something we should consider cleaning up?

--m

**Comment by zankavrogin** [comment]
hey @michaelshmitty,
The duplicated commands you mentioned have been removed. 

The reason for the multiple commands for the basically same thing has to do with compatibility with the node-ardrone library. We include our own commands because we feel like `forward()` makes a little more sense.

**Comment by michaelshmitty** [comment]
Cheers!
